apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-component
    app.kubernetes.io/part-of: blue-dolphin
  name: quarkus-component
  namespace: pdave
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: quarkus-component
status:
  loadBalancer: {}
